import "./globals.css";
import { Raleway } from "next/font/google";
import type { Metadata } from "next";
import Nav from "./components/Nav";

const inter = Raleway({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Nav />
        <div className="pt-[5rem] bg-background">{children}</div>
      </body>
    </html>
  );
}
